basePath: /api/v1
definitions:
  dto.CollectorDto:
    properties:
      alertCnt:
        type: integer
      alertUrl:
        type: string
      appId:
        type: integer
      cluster:
        type: string
      description:
        type: string
      enabled:
        type: integer
      envId:
        type: integer
      envName:
        type: string
      execCnt:
        type: integer
      heartBeatInterval:
        type: integer
      heartBeatUrl:
        type: string
      metricUrl:
        type: string
      name:
        type: string
      planId:
        type: integer
      projectCode:
        type: string
      projectId:
        type: integer
      tokenRefreshInterval:
        type: integer
      tokenUrl:
        type: string
    required:
    - cluster
    - envId
    - name
    - planId
    - projectId
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  termsOfService: http://127.0.0.1:8080
  title: GinDemo
  version: "1.0"
paths:
  /api/v1/collectors:
    get:
      description: 查询采集器列表
      parameters:
      - description: 页数
        in: query
        name: PageNum
        type: integer
      - description: 页大小
        in: query
        name: PageSize
        type: integer
      responses:
        "200":
          description: ""
      tags:
      - Collector
    post:
      description: 创建采集器
      parameters:
      - description: 创建参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CollectorDto'
      responses:
        "200":
          description: ""
      tags:
      - Collector
  /api/v1/projects:
    get:
      description: 查询项目列表
      parameters:
      - description: 操作描述
        in: formData
        name: description
        type: string
      - description: 开始时间
        in: formData
        name: start_time
        type: string
      - description: 结束时间
        in: formData
        name: end_time
        type: string
      - description: 页数
        in: formData
        name: page
        required: true
        type: string
      - description: 数据条数
        in: formData
        name: size
        required: true
        type: string
      responses:
        "200":
          description: ""
      tags:
      - Project
  /api/v1/users:
    get:
      description: 查询用户列表
      parameters:
      - description: 操作者
        in: query
        name: operator
        type: string
      - description: 操作描述
        in: query
        name: description
        type: string
      - description: 开始时间
        in: query
        name: start_time
        type: string
      - description: 结束时间
        in: query
        name: end_time
        type: string
      responses:
        "200":
          description: ""
      tags:
      - User
swagger: "2.0"
